# Generated by Django 5.0.1 on 2024-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
